[WIP]新規投稿機能の実装開始
yu19921015/nuxt_tweet pull request #2
Opened 2019-05-19 21:54 UTC by yu19921015

2019-05-21 11:30 UTC, takao-sone requested changes
レビューしました、概ね良いと思います！

2019-05-21 11:30 UTC, takao-sone commented on nuxt_tweet/pages/posts/new.vue
> +      <button type="submit" value="投稿" @click.prevent="submit">投稿</button>
buttonタグのvalueは何を意味してる？
いらないなら取ってしまってください。
何か意図あるなら説明くれると。

2019-05-21 11:30 UTC, takao-sone commented on nuxt_tweet/pages/posts/new.vue
> +        await this.createPost({payload});
例外処理として、エラーの場合にブラウザのconsoleにエラー内容を表示するようにしてください。

2019-05-21 11:48 UTC, yu19921015 commented on nuxt_tweet/pages/posts/new.vue
> +      <button type="submit" value="投稿" @click.prevent="submit">投稿</button>
必要ないので削除しました。

2019-05-21 11:48 UTC, yu19921015 commented on nuxt_tweet/pages/posts/new.vue
> +        await this.createPost({payload});
エラーの場合に、エラー内容をコンソールに出力するように修正しました。

2019-05-21 11:49 UTC, yu19921015 commented
レビューの指摘に対応しました。
際レビューをよろしくお願いします。

2019-05-21 11:57 UTC, takao-sone approved these changes
修正時のコミットメッセージ、いいと思います！
コメントしたのでそこの箇所だけ対応したらマージして次の機能に移ってください

2019-05-21 11:57 UTC, takao-sone commented on nuxt_tweet/pages/posts/new.vue
> +          const payload = {...this.newPost};
try-catchで囲む場所はできるだけ小さく（エラーが出る範囲だけ）するのが良いコーディング。
ここで言えば `const payload = {...this.newPost}` はエラー出そうにないのでtryのスコープから出すべきかな。

2019-05-22 11:16 UTC, yu19921015 commented on nuxt_tweet/pages/posts/new.vue
> +          const payload = {...this.newPost};
const payload = {...this.newPost}
をtry句から外しました。

2019-05-22 11:17 UTC, yu19921015 commented
修正が完了したので、masterブランチにマージ済。

2019-05-22 11:22 UTC, merged